import os

from src.constants import *


FONT_PATH = 'res/fonts'

ORIGINAL_FONT_FILE = 'original.ttf'
ORIGINAL_FONT_PATH = os.path.join(FONT_PATH, 'original.ttf')
ORIGINAL_FONT_SIZE = 60
ORIGINAL_FONT_SHADOW = (1, 1)
ORIGINAL_FONT_CENTER_X = WIN_WIDTH /2
ORIGINAL_FONT_CENTER_Y = 75
ORIGINAL_FONT_CENTER = (ORIGINAL_FONT_CENTER_X, ORIGINAL_FONT_CENTER_Y)
ORIGINAL_FONT_OUTLINE_WIDTH = 1
